### ISSUE TITLE
Roadmap to 3.0.0

### ISSUE THREAD

**Issue by markusenglund** [balloob/react-sidebar#156]
This is an updated list of the features and fixes I ideally want to have implemented before the next major release. 
I'd really appreciate it if anyone would want to help out with any of these issues.

* [x] Find a solution to the various problems people are facing related to scrolling. #145 #130 #113 #111 #77. #86 might help solving it. EDIT: Created PR #161 to solve this!
* [x] Remove the sidebar's box-shadow when the sidebar is hidden #115. EDIT: Fixed in #162 
* [x] Solve IOS swipe issue #67. EDIT: Swiping removed in IOS #164 
* [ ] Document new features and create types for new API in [the definitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-sidebar)

EDIT: Removed some items

**Comment by j10sanders** [comment]
Unfortunately, I don't think that scrolling works yet.  Try making your browser window small enough, and running window.scrollTo(0, 0)

http://balloob.github.io/react-sidebar/example/

**Comment by markusenglund** [comment]
You're right. I fixed it in #161, but I ended up not publishing the change in v3.0. I figured that the change might break a bunch of different use cases that I maybe didn't foresee.

I'll still publish it eventually (in new major release in that case) since I believe the current scrolling behaviour has serious issues.

**Comment by rtman** [comment]
looking forward to this
